[package]
name = "tls"
version = "0.3.5"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.16", features = ["derive"] }
rs_merkle = "1.4.2"
serde = { version = "1.0", features= ["derive"] }
serde_json = "1.0.127"
