[package]
name = "tls"
<<<<<<< HEAD
version = "0.3.8"
=======
version = "0.3.8"
>>>>>>> 6c62802dcd749cffc2550ae0a58859849d26e715
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.16", features = ["derive"] }
hex = "0.4.3"
rs_merkle = "1.4.2"
serde = { version = "1.0", features= ["derive"] }
serde_json = "1.0.127"
sha2 = "0.10.8"
